language: csharp
solution: WeihanLi.AspNetMvc.MvcSimplePager.sln
# runtime config
mono: none
dotnet: 5.0.102
dist: bionic

install:
  - dotnet --info
  - dotnet restore
  
script:
  - dotnet build /p:Configuration=Release --framework:netstandard2.0 ./src//WeihanLi.AspNetMvc.MvcSimplePager/WeihanLi.AspNetMvc.MvcSimplePager.csproj
