language: csharp
solution: MvcSimplePager.sln
# runtime config
mono: latest
dotnet: 1.0.4
dist: trusty

install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ./MvcSimplePager.Test/MvcSimplePager.Test.csproj
