language: csharp
solution: MvcSimplePager.sln
mono: latest
install:
  - nuget restore MvcSimplePager.sln
  - nuget install xunit.runner.console -Version 2.2.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ./MvcSimplePager/MvcSimplePager.csproj
  - msbuild /p:Configuration=Release ./MvcSimplePager.Test/MvcSimplePager.Test.csproj
  - mono ./testrunner/xunit.runner.console.2.2.0/tools/xunit.console.exe ./MvcSimplePager.Test/bin/Release/MvcSimplePager.Test.dll
