language: csharp
solution: WeihanLi.AspNetMvc.MvcSimplePager.sln
# runtime config
mono: none
dotnet: 2.0.0
dist: trusty

install:
  - dotnet --info
  - dotnet restore
  
script:
  - dotnet build /p:Configuration=Release --framework:netstandard2.0 ./WeihanLi.AspNetMvc.MvcSimplePager/WeihanLi.AspNetMvc.MvcSimplePager.csproj
  - dotnet test ./WeihanLi.AspNetMvc.MvcSimplePager.Test/WeihanLi.AspNetMvc.MvcSimplePager.Test.csproj