# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
# version: 1.0.{build}

# you can use {branch} name in version format too
version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - netstandard
    - production
    - dev

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false

# Skipping commits with particular message or from specific user
skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/      # Regex for matching commit message
  # author: weihanli                                # Commit author's username, name, email or regexp maching one of these.
  # Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
  files:
    - docs/*
    - '**/*.html'
    - '**/*.md'

# Including commits with particular message or from specific user
only_commits:
  message: /build/                # Start a new build if message contains 'build'
  author: weihanli@outlook.com        # Start a new build for commit of user with email jack@company.com

# Including commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
#  files:
#    - Project-A/
#    - Project-B/

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '2.0.0'

# Build worker image (VM template)
image: Visual Studio 2017

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Release

# scripts to run before build
before_build:
  - dotnet --info
  - dotnet restore
# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:
  
# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - dotnet build
# to disable automatic builds
#build: off

#---------------------------------#		
#       tests configuration       #		
#---------------------------------#		

# scripts to run before tests
before_test:
  - nuget install xunit.runner.console -Version 2.2.0 -OutputDirectory testrunner
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory openCover

# scripts to run after tests
after_test:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "MvcSimplePager_coverage.xml" -t fccda60c-9cc3-446e-a7fb-98f5c179cda1
  
# to run your custom scripts instead of automatic tests
test_script:
  - dotnet test .\MvcSimplePager.Test\MvcSimplePager.Test.csproj
  - .\openCover\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\testrunner\xunit.runner.console.2.2.0\tools\xunit.console.exe" -targetargs:".\MvcSimplePager.Test\bin\Debug\netcoreapp1.1\MvcSimplePager.Test.dll -noshadow" -excludebyattribute:*.ExcludeFromCodeCoverage* -output:".\MvcSimplePager_coverage.xml"
  
# to disable automatic tests
#test: off